<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-07-14 21:43

$extensionPath = t3lib_extMgm::extPath('powermail2document');
$extensionClassesPath = t3lib_extMgm::extPath('powermail2document') . 'Classes/';
return array(
	'tx_powermail2document_extmgm_configuration_donate' => $extensionClassesPath . 'ExtMgm/Configuration/Donate.php',
	'tx_powermail2document_filetypes_csv' => $extensionClassesPath . 'FileTypes/Csv.php',
	'tx_powermail2document_filetypes_docx' => $extensionClassesPath . 'FileTypes/Docx.php',
	'tx_powermail2document_filetypes_fluid' => $extensionClassesPath . 'FileTypes/Fluid.php',
	'tx_powermail2document_filetypes_htm' => $extensionClassesPath . 'FileTypes/Htm.php',
	'tx_powermail2document_filetypes_html' => $extensionClassesPath . 'FileTypes/Html.php',
	'tx_powermail2document_filetypes_odg' => $extensionClassesPath . 'FileTypes/Odg.php',
	'tx_powermail2document_filetypes_ods' => $extensionClassesPath . 'FileTypes/Ods.php',
	'tx_powermail2document_filetypes_odt' => $extensionClassesPath . 'FileTypes/Odt.php',
	'tx_powermail2document_filetypes_pdf' => $extensionClassesPath . 'FileTypes/Pdf.php',
	'tx_powermail2document_filetypes_pptx' => $extensionClassesPath . 'FileTypes/Pptx.php',
	'tx_powermail2document_filetypes_rtf' => $extensionClassesPath . 'FileTypes/Rtf.php',
	'tx_powermail2document_filetypes_txt' => $extensionClassesPath . 'FileTypes/Txt.php',
	'tx_powermail2document_filetypes_unknownfileending' => $extensionClassesPath . 'FileTypes/UnknownFileEnding.php',
	'tx_powermail2document_filetypes_xlsx' => $extensionClassesPath . 'FileTypes/Xlsx.php',
	'tx_powermail2document_filetypes_xml' => $extensionClassesPath . 'FileTypes/Xml.php',
	'tx_powermail2document_filetypes_abstract_file' => $extensionClassesPath . 'FileTypes/Abstract/File.php',
	'tx_powermail2document_filetypes_abstract_zipwithxml' => $extensionClassesPath . 'FileTypes/Abstract/ZipWithXml.php',
	'tx_powermail2document_filetypes_pdf_formfiller' => $extensionClassesPath . 'FileTypes/Pdf/FormFiller.php',
	'tx_powermail2document_hooks_powermail_marker_markerarray' => $extensionClassesPath . 'Hooks/Powermail/Markers/MarkerArray.php',
	'tx_powermail2document_hooks_powermail_submit_submitemailhook2' => $extensionClassesPath . 'Hooks/Powermail/Submit/SubmitEmailHook2.php',
	'tx_powermail2document_util_list' => $extensionClassesPath . 'Util/List.php',
);
?>